const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'app', 'i18n', 'locales');
const newKeys = {
  es: { justNow: "hace un momento", minAgo: "hace {n} min", hAgo: "hace {n} h", yesterday: "Ayer", chatTab: "Chat", noTeamsChatTitle: "No estás en ningún equipo.", noTeamsChatDesc: "Únete a un equipo para chatear.", goToTeamsBtn: "Ir a Equipos", noMessagesYet: "Sin mensajes...", chatPoll: "Encuesta", chatLocation: "Ubicación", chatAttachment: "Adjunto", send: "Escribe un mensaje", chatParticipants: "Participantes del chat", chatDayToday: "HOY", chatDayYesterday: "AYER", noParticipants: "Sin participantes.", tapForParticipants: "Toca para ver los participantes", adminBadge: "Admin", onlineRecent: "En línea", offline: "Desconectado/a", pollTitle: "Envió una encuesta.", locationTitle: "Envió una ubicación.", openInMaps: "Abrir en Google Maps", viewVotes: "Ver votos", pollQuestionPlaceholder: "¿Cuál es la pregunta?", pollAnswerPlaceholder: "Respuesta", addOption: "Añadir opción", publish: "Publicar", eventNamePlaceholder: "Nombre del evento...", createEventBtn: "Crear evento", eventError: "Error al crear.", geoNotSupported: "Su navegador no admite la geolocalización.", geoError: "No se puede obtener la ubicación.", shareLocationBtn: "Compartir ubicación", deleteMessageConfirm: "¿Seguro que quieres eliminar esto?", loadingOldMessages: "Cargando mensajes anteriores...", chatEmptyTitle: "Está completamente tranquilo...", chatEmptyDesc: "¡Sé el primero en enviar un mensaje a tu equipo!", newMessagesBadge: "Nuevos mensajes", totalVotes: "Total", noVotesYet: "Sin votos.", msgVotePlural1: "{n} voto", msgVotePlural2: "{n} votos", msgVotePlural3: "{n} votos", msgVotePlural5: "{n} votos" },
  fr: { justNow: "à l'instant", minAgo: "il y a {n} min", hAgo: "il y a {n} h", yesterday: "Hier", chatTab: "Chat", noTeamsChatTitle: "Vous n'êtes dans aucune équipe.", noTeamsChatDesc: "Rejoignez une équipe pour discuter.", goToTeamsBtn: "Aller aux Équipes", noMessagesYet: "Pas de messages...", chatPoll: "Sondage", chatLocation: "Emplacement", chatAttachment: "Pièce jointe", send: "Écrivez un message", chatParticipants: "Participants au chat", chatDayToday: "AUJOURD'HUI", chatDayYesterday: "HIER", noParticipants: "Aucun participant.", tapForParticipants: "Appuyez pour voir les participants", adminBadge: "Admin", onlineRecent: "En ligne", offline: "Hors ligne", pollTitle: "A envoyé un sondage.", locationTitle: "A envoyé un emplacement.", openInMaps: "Ouvrir dans Google Maps", viewVotes: "Voir les votes", pollQuestionPlaceholder: "Quelle est la question ?", pollAnswerPlaceholder: "Réponse", addOption: "Ajouter une option", publish: "Publier", eventNamePlaceholder: "Nom de l'événement...", createEventBtn: "Créer un événement", eventError: "Erreur.", geoNotSupported: "La géolocalisation n'est pas prise en charge.", geoError: "Impossible d'obtenir la position.", shareLocationBtn: "Partager la position", deleteMessageConfirm: "Voulez-vous vraiment supprimer ce message ?", loadingOldMessages: "Chargement des messages...", chatEmptyTitle: "C'est complètement calme...", chatEmptyDesc: "Soyez le premier à envoyer un message à votre équipe !", newMessagesBadge: "Nouveaux messages", totalVotes: "Total", noVotesYet: "Aucun vote.", msgVotePlural1: "{n} vote", msgVotePlural2: "{n} votes", msgVotePlural3: "{n} votes", msgVotePlural5: "{n} votes" },
  nl: { justNow: "zojuist", minAgo: "{n} min geleden", hAgo: "{n} u geleden", yesterday: "Gisteren", chatTab: "Chat", noTeamsChatTitle: "Je zit in geen enkel team.", noTeamsChatDesc: "Word lid van of maak een team aan om te chatten.", goToTeamsBtn: "Ga naar Teams", noMessagesYet: "Nog geen berichten ...", chatPoll: "Peiling", chatLocation: "Locatie", chatAttachment: "Bijlage", send: "Typ een bericht", chatParticipants: "Chatdeelnemers", chatDayToday: "VANDAAG", chatDayYesterday: "GISTEREN", noParticipants: "Geen deelnemers.", tapForParticipants: "Tik voor deelnemers", adminBadge: "Admin", onlineRecent: "Online", offline: "Offline", pollTitle: "Heeft een peiling gestuurd.", locationTitle: "Heeft een locatie gestuurd.", openInMaps: "Openen in Google Maps", viewVotes: "Bekijk stemmen", pollQuestionPlaceholder: "Wat is de vraag?", pollAnswerPlaceholder: "Antwoord", addOption: "Optie toevoegen", publish: "Publiceren", eventNamePlaceholder: "Naam evenement...", createEventBtn: "Evenement aanmaken", eventError: "Fout.", geoNotSupported: "Geolocatie wordt niet ondersteund.", geoError: "Kan locatie niet ophalen.", shareLocationBtn: "Locatie delen", deleteMessageConfirm: "Weet je zeker dat je dit wilt verwijderen?", loadingOldMessages: "Berichten laden...", chatEmptyTitle: "Het is hier stil...", chatEmptyDesc: "Wees de eerste die een bericht naar je team stuurt!", newMessagesBadge: "Nieuwe berichten", totalVotes: "Totaal", noVotesYet: "Geen stemmen.", msgVotePlural1: "{n} stem", msgVotePlural2: "{n} stemmen", msgVotePlural3: "{n} stemmen", msgVotePlural5: "{n} stemmen" },
  tr: { justNow: "şimdi", minAgo: "{n} dk önce", hAgo: "{n} sa önce", yesterday: "Dün", chatTab: "Sohbet", noTeamsChatTitle: "Hiçbir takımda değilsiniz.", noTeamsChatDesc: "Sohbet etmek için takıma katılın.", goToTeamsBtn: "Takımlara Git", noMessagesYet: "Henüz mesaj yok ...", chatPoll: "Anket", chatLocation: "Konum", chatAttachment: "Ek", send: "Mesaj yazın", chatParticipants: "Sohbet Katılımcıları", chatDayToday: "BUGÜN", chatDayYesterday: "DÜN", noParticipants: "Katılımcı yok.", tapForParticipants: "Katılımcılar için dokunun", adminBadge: "Yönetici", onlineRecent: "Çevrimiçi", offline: "Çevrimdışı", pollTitle: "Bir anket gönderdi.", locationTitle: "Bir konum gönderdi.", openInMaps: "Google Haritalar'da aç", viewVotes: "Oyları görüntüle", pollQuestionPlaceholder: "Soru nedir?", pollAnswerPlaceholder: "Cevap", addOption: "Seçenek ekle", publish: "Yayınla", eventNamePlaceholder: "Etkinlik adı...", createEventBtn: "Etkinlik Oluştur", eventError: "Etkinlik oluşturulamadı.", geoNotSupported: "Coğrafi konum desteklenmiyor.", geoError: "Konum alınamıyor.", shareLocationBtn: "Konumu paylaş", deleteMessageConfirm: "Bu mesajı silmek istediğinize emin misiniz?", loadingOldMessages: "Eski mesajlar yükleniyor...", chatEmptyTitle: "Burası sessiz...", chatEmptyDesc: "Takımınıza mesaj gönderen ilk kişi siz olun!", newMessagesBadge: "Yeni mesajlar", totalVotes: "Toplam", noVotesYet: "Oy yok.", msgVotePlural1: "{n} oy", msgVotePlural2: "{n} oy", msgVotePlural3: "{n} oy", msgVotePlural5: "{n} oy" },
  ar: { justNow: "الآن", minAgo: "منذ {n} دقيقة", hAgo: "منذ {n} ساعة", yesterday: "أمس", chatTab: "دردشة", noTeamsChatTitle: "أنت لست في أي فريق.", noTeamsChatDesc: "انضم إلى فريق للدردشة.", goToTeamsBtn: "الفرق", noMessagesYet: "لا رسائل ...", chatPoll: "استطلاع", chatLocation: "موقع", chatAttachment: "مرفق", send: "اكتب رسالة", chatParticipants: "المشاركون في الدردشة", chatDayToday: "اليوم", chatDayYesterday: "أمس", noParticipants: "لا مشاركين.", tapForParticipants: "انقر للمشاركين", adminBadge: "مسؤول", onlineRecent: "متصل", offline: "غير متصل", pollTitle: "أرسل استطلاعًا.", locationTitle: "أرسل موقعًا.", openInMaps: "الفتح في خرائط جوجل", viewVotes: "عرض الأصوات", pollQuestionPlaceholder: "السؤال؟", pollAnswerPlaceholder: "إجابة", addOption: "إضافة خيار", publish: "نشر", eventNamePlaceholder: "اسم الحدث...", createEventBtn: "إنشاء حدث", eventError: "خطأ", geoNotSupported: "غير مدعوم", geoError: "لا يمكن الحصول على الموقع.", shareLocationBtn: "مشاركة الموقع", deleteMessageConfirm: "حذف الرسالة؟", loadingOldMessages: "تحميل...", chatEmptyTitle: "هادئ تمامًا...", chatEmptyDesc: "أرسل رسالة!", newMessagesBadge: "رسائل جديدة", totalVotes: "المجموع", noVotesYet: "لا أصوات.", msgVotePlural1: "{n} صوت", msgVotePlural2: "{n} أصوات", msgVotePlural3: "{n} أصوات", msgVotePlural5: "{n} صوت" },
  el: { send: "Πληκτρολογήστε ένα μήνυμα", chatParticipants: "Συμμετέχοντες στη συνομιλία", chatDayToday: "ΣΗΜΕΡΑ", chatDayYesterday: "ΧΘΕΣ", noParticipants: "Κανένας συμμετέχων.", tapForParticipants: "Πατήστε για συμμετέχοντες", adminBadge: "Admin", onlineRecent: "Συνδεδεμένος", offline: "Εκτός σύνδεσης", pollTitle: "Έστειλε μια δημοσκόπηση.", locationTitle: "Έστειλε μια τοποθεσία.", openInMaps: "Άνοιγμα στους Χάρτες Google", viewVotes: "Προβολή ψήφων", pollQuestionPlaceholder: "Ποια είναι η ερώτηση;", pollAnswerPlaceholder: "Απάντηση", addOption: "Προσθήκη επιλογής", publish: "Δημοσιεύω", eventNamePlaceholder: "Όνομα εκδήλωσης...", createEventBtn: "Δημιουργία συμβάντος", eventError: "Σφάλμα.", geoNotSupported: "Δεν υποστηρίζεται.", geoError: "Αδυναμία λήψης τοποθεσίας.", shareLocationBtn: "Κοινή χρήση τοποθεσίας", deleteMessageConfirm: "Διαγραφή αυτού του μηνύματος;", loadingOldMessages: "Φόρτωση μηνυμάτων...", chatEmptyTitle: "Είναι εντελώς ήσυχα εδώ...", chatEmptyDesc: "Γίνε ο πρώτος που θα στείλει ένα μήνυμα!", newMessagesBadge: "Νέα μηνύματα", totalVotes: "Σύνολο", noVotesYet: "Καμία ψήφος.", msgVotePlural1: "{n} ψήφος", msgVotePlural2: "{n} ψήφοι", msgVotePlural3: "{n} ψήφοι", msgVotePlural5: "{n} ψήφοι" }
};

newKeys.mx = newKeys.es;

for (const [lang, dict] of Object.entries(newKeys)) {
  const filePath = path.join(localesDir, `${lang}.ts`);
  if (fs.existsSync(filePath)) {
    let content = fs.readFileSync(filePath, 'utf-8');
    for (const [k, v] of Object.entries(dict)) {
      const regex = new RegExp(`(${k}:\\s*")[^"]*(")`);
      if (regex.test(content)) {
        content = content.replace(regex, `$1${v}$2`);
      } else {
         content = content.replace(/};\s*$/, `  ${k}: "${v}",\n};`);
      }
    }
    fs.writeFileSync(filePath, content);
  }
}
