const fs = require('fs');
const path = require('path');

const localesDir = path.join(process.cwd(), 'src', 'app', 'i18n', 'locales');

const masterDict = {
  en: { chatTab: 'Chat', noTeamsChatTitle: 'You are not in any team yet.', noTeamsChatDesc: 'Join a team or create a new one to chat.', goToTeamsBtn: 'Go to Teams', noMessagesYet: 'No messages yet...', chatPoll: 'Poll', chatLocation: 'Location', chatAttachment: 'Attachment', chatDayToday: 'TODAY', chatDayYesterday: 'YESTERDAY', newMessagesBadge: 'New messages', chatTextTab: 'Text', chatEventTab: 'Event', chatLocationTab: 'Location', pollQuestionPlaceholder: 'What is the question?...', pollAnswerPlaceholder: 'Answer', addOption: 'Add option', publish: 'Publish', eventNamePlaceholder: 'Event name', createEventBtn: 'Create Event', shareLocationBtn: 'Share location', chatParticipants: 'Chat Participants', noParticipants: 'No participants.', adminBadge: 'Admin', onlineRecent: 'Online recently', offline: 'Offline', totalVotes: 'Total', noVotesYet: 'No votes.', msgVotePlural1: '{n} vote', msgVotePlural2: '{n} votes', msgVotePlural3: '{n} votes', msgVotePlural5: '{n} votes', chatPollSent: 'Sent a poll.', chatEventError: 'Error creating event.', chatGeoNotSupported: 'Geolocation is not supported.', chatLocationSent: 'Sent a location.', chatGeoError: 'Cannot retrieve location.', chatDeleteConfirm: 'Delete this message?', loadingOldMessages: 'Loading older messages...', chatEmptyTitle: 'It is very quiet here...', chatEmptyDesc: 'Be the first to send a message!', openInMaps: 'Open in Google Maps', viewVotes: 'View votes', team: 'Team', tapForParticipants: 'Tap for participants', allUsers: 'All', userDefault: 'User', quickTexts: `["You sucked today! 👎", "Good game! 👏", "Beers on you! 🍻", "Late again! ⏳", "Party pooper!", "Who has the ball?", "Excuses again...", "Ref's fault! 🙈", "Where is the stamina? 🥵", "All in! 💪", "We need a sub! 🔄"]` },
  de: { chatTab: 'Chat', noTeamsChatTitle: 'Sie sind noch in keinem Team.', noTeamsChatDesc: 'Treten Sie einem Team bei oder erstellen Sie eines, um zu chatten.', goToTeamsBtn: 'Gehe zu Teams', noMessagesYet: 'Noch keine Nachrichten...', chatPoll: 'Umfrage', chatLocation: 'Standort', chatAttachment: 'Anhang', chatDayToday: 'HEUTE', chatDayYesterday: 'GESTERN', newMessagesBadge: 'Neue Nachrichten', chatTextTab: 'Text', chatEventTab: 'Event', chatLocationTab: 'Standort', pollQuestionPlaceholder: 'Wie lautet die Frage?...', pollAnswerPlaceholder: 'Antwort', addOption: 'Option hinzufügen', publish: 'Veröffentlichen', eventNamePlaceholder: 'Event-Name', createEventBtn: 'Event erstellen', shareLocationBtn: 'Standort teilen', chatParticipants: 'Chat-Teilnehmer', noParticipants: 'Keine Teilnehmer.', adminBadge: 'Admin', onlineRecent: 'Zuletzt online', offline: 'Offline', totalVotes: 'Gesamt', noVotesYet: 'Keine Stimmen.', msgVotePlural1: '{n} Stimme', msgVotePlural2: '{n} Stimmen', msgVotePlural3: '{n} Stimmen', msgVotePlural5: '{n} Stimmen', chatPollSent: 'Hat eine Umfrage gesendet.', chatEventError: 'Fehler beim Erstellen des Events.', chatGeoNotSupported: 'Geolokalisierung wird nicht unterstützt.', chatLocationSent: 'Hat einen Standort gesendet.', chatGeoError: 'Standort kann nicht abgerufen werden.', chatDeleteConfirm: 'Nachricht löschen?', loadingOldMessages: 'Ältere Nachrichten laden...', chatEmptyTitle: 'Hier ist es sehr ruhig...', chatEmptyDesc: 'Seien Sie der Erste!', openInMaps: 'In Google Maps öffnen', viewVotes: 'Stimmen ansehen', team: 'Team', tapForParticipants: 'Tippen für Teilnehmer', allUsers: 'Alle', userDefault: 'Benutzer', quickTexts: `["Du warst heute mies! 👎", "Gutes Spiel! 👏", "Du gibst ein Bier aus! 🍻", "Schon wieder zu spät! ⏳", "Spielverderber!", "Wer hat den Ball?", "Wieder Ausreden...", "Der Schiri ist schuld! 🙈", "Wo ist die Ausdauer? 🥵", "Alles geben! 💪", "Wir brauchen einen Wechsel! 🔄"]` },
  it: { chatTab: 'Chat', noTeamsChatTitle: 'Non sei ancora in nessuna squadra.', noTeamsChatDesc: 'Unisciti a una squadra.', goToTeamsBtn: 'Vai alle Squadre', noMessagesYet: 'Ancora nessun messaggio...', chatPoll: 'Sondaggio', chatLocation: 'Posizione', chatAttachment: 'Allegato', chatDayToday: 'OGGI', chatDayYesterday: 'IERI', newMessagesBadge: 'Nuovi messaggi', chatTextTab: 'Testo', chatEventTab: 'Evento', chatLocationTab: 'Posizione', pollQuestionPlaceholder: 'Qual è la domanda?...', pollAnswerPlaceholder: 'Risposta', addOption: 'Aggiungi opzione', publish: 'Pubblica', eventNamePlaceholder: 'Nome evento', createEventBtn: 'Crea evento', shareLocationBtn: 'Condividi posizione', chatParticipants: 'Partecipanti alla chat', noParticipants: 'Nessun partecipante.', adminBadge: 'Admin', onlineRecent: 'Online di recente', offline: 'Offline', totalVotes: 'Totale', noVotesYet: 'Nessun voto.', msgVotePlural1: '{n} voto', msgVotePlural2: '{n} voti', msgVotePlural3: '{n} voti', msgVotePlural5: '{n} voti', chatPollSent: 'Ha inviato un sondaggio.', chatEventError: 'Errore durante la creazione.', chatGeoNotSupported: 'La geolocalizzazione non è supportata.', chatLocationSent: 'Ha inviato una posizione.', chatGeoError: 'Impossibile recuperare la posizione.', chatDeleteConfirm: 'Eliminare questo messaggio?', loadingOldMessages: 'Caricamento...', chatEmptyTitle: 'È molto tranquillo qui...', chatEmptyDesc: 'Sii il primo!', openInMaps: 'Apri in Google Maps', viewVotes: 'Vedi i voti', team: 'Squadra', tapForParticipants: 'Tocca per i partecipanti', allUsers: 'Tutti', userDefault: 'Utente', quickTexts: `["Oggi hai fatto schifo! 👎", "Bella partita! 👏", "Offri una birra! 🍻", "Di nuovo in ritardo! ⏳", "Guastafeste!", "Chi ha la palla?", "Di nuovo scuse...", "Colpa dell'arbitro! 🙈", "Dov'è la resistenza? 🥵", "Tutto dentro! 💪", "Ci serve un cambio! 🔄"]` },
  hr: { chatTab: 'Chat', noTeamsChatTitle: 'Trenutno niste u nijednoj ekipi.', noTeamsChatDesc: 'Za razgovor se pridružite ekipi.', goToTeamsBtn: 'Idi na Ekipe', noMessagesYet: 'Nema poruka...', chatPoll: 'Anketa', chatLocation: 'Lokacija', chatAttachment: 'Privitak', chatDayToday: 'DANAS', chatDayYesterday: 'JUČER', newMessagesBadge: 'Nove poruke', chatTextTab: 'Tekst', chatEventTab: 'Događaj', chatLocationTab: 'Lokacija', pollQuestionPlaceholder: 'Kako glasi pitanje?...', pollAnswerPlaceholder: 'Odgovor', addOption: 'Dodaj opciju', publish: 'Objavi', eventNamePlaceholder: 'Ime događaja', createEventBtn: 'Stvori događaj', shareLocationBtn: 'Podijeli lokaciju', chatParticipants: 'Sudionici', noParticipants: 'Nema sudionika.', adminBadge: 'Admin', onlineRecent: 'Nedavno na mreži', offline: 'Izvan mreže', totalVotes: 'Ukupno', noVotesYet: 'Nema glasova.', msgVotePlural1: '{n} glas', msgVotePlural2: '{n} glasa', msgVotePlural3: '{n} glasova', msgVotePlural5: '{n} glasova', chatPollSent: 'Poslao/la je anketu.', chatEventError: 'Greška pri stvaranju.', chatGeoNotSupported: 'Nije podržano.', chatLocationSent: 'Poslao/la je lokaciju.', chatGeoError: 'Ne mogu dobiti lokaciju.', chatDeleteConfirm: 'Izbrisati poruku?', loadingOldMessages: 'Učitavanje...', chatEmptyTitle: 'Ovdje je potpuno tiho...', chatEmptyDesc: 'Budi prvi!', openInMaps: 'Otvori u Google Maps', viewVotes: 'Pregled glasova', team: 'Ekipa', tapForParticipants: 'Dodirni za sudionike', allUsers: 'Svi', userDefault: 'Korisnik', quickTexts: `["Danas si bio loš! 👎", "Dobra igra! 👏", "Plaćaš pivo! 🍻", "Opet kasniš! ⏳", "Kvariigra!", "Tko ima loptu?", "Opet izgovori...", "Sudac je kriv! 🙈", "Gdje je kondicija? 🥵", "Idemo na maksimum! 💪", "Trebamo zamjenu! 🔄"]` },
  sr: { chatTab: 'Chat', noTeamsChatTitle: 'Trenutno niste u nijednoj ekipi.', noTeamsChatDesc: 'Za razgovor se pridružite ekipi.', goToTeamsBtn: 'Ide na Ekipe', noMessagesYet: 'Nema poruka...', chatPoll: 'Anketa', chatLocation: 'Lokacija', chatAttachment: 'Prilog', chatDayToday: 'DANAS', chatDayYesterday: 'JUČE', newMessagesBadge: 'Nove poruke', chatTextTab: 'Tekst', chatEventTab: 'Događaj', chatLocationTab: 'Lokacija', pollQuestionPlaceholder: 'Kako glasi pitanje?...', pollAnswerPlaceholder: 'Odgovor', addOption: 'Dodaj opciju', publish: 'Objavi', eventNamePlaceholder: 'Ime događaja', createEventBtn: 'Kreiraj događaj', shareLocationBtn: 'Podeli lokaciju', chatParticipants: 'Učesnici', noParticipants: 'Nema učesnika.', adminBadge: 'Admin', onlineRecent: 'Nedavno na mreži', offline: 'Van mreže', totalVotes: 'Ukupno', noVotesYet: 'Nema glasova.', msgVotePlural1: '{n} glas', msgVotePlural2: '{n} glasa', msgVotePlural3: '{n} glasova', msgVotePlural5: '{n} glasova', chatPollSent: 'Poslao/la je anketu.', chatEventError: 'Greška pri kreiranju.', chatGeoNotSupported: 'Nije podržano.', chatLocationSent: 'Poslao/la je lokaciju.', chatGeoError: 'Ne mogu da dobijem lokaciju.', chatDeleteConfirm: 'Izbrisati poruku?', loadingOldMessages: 'Učitavanje...', chatEmptyTitle: 'Ovde je potpuno tiho...', chatEmptyDesc: 'Budi prvi!', openInMaps: 'Otvori u Google Maps', viewVotes: 'Pregled glasova', team: 'Ekipa', tapForParticipants: 'Dodirni za učesnike', allUsers: 'Svi', userDefault: 'Korisnik', quickTexts: `["Danas si bio loš! 👎", "Dobra igra! 👏", "Plaćaš pivo! 🍻", "Opet kasniš! ⏳", "Kvariigra!", "Ko ima loptu?", "Opet izgovori...", "Sudija je kriv! 🙈", "Gde je kondicija? 🥵", "Idemo na maksimum! 💪", "Treba nam izmena! 🔄"]` },
  es: { chatTab: 'Chat', noTeamsChatTitle: 'Aún no estás en ningún equipo.', noTeamsChatDesc: 'Únete a un equipo o crea uno nuevo para chatear.', goToTeamsBtn: 'Ir a Equipos', noMessagesYet: 'No hay mensajes aún...', chatPoll: 'Encuesta', chatLocation: 'Ubicación', chatAttachment: 'Archivo adjunto', chatDayToday: 'HOY', chatDayYesterday: 'AYER', newMessagesBadge: 'Nuevos mensajes', chatTextTab: 'Texto', chatEventTab: 'Evento', chatLocationTab: 'Ubicación', pollQuestionPlaceholder: '¿Cuál es la pregunta?...', pollAnswerPlaceholder: 'Respuesta', addOption: 'Añadir opción', publish: 'Publicar', eventNamePlaceholder: 'Nombre del evento', createEventBtn: 'Crear Evento', shareLocationBtn: 'Compartir ubicación', chatParticipants: 'Participantes del chat', noParticipants: 'Sin participantes.', adminBadge: 'Admin', onlineRecent: 'En línea', offline: 'Desconectado/a', totalVotes: 'Total', noVotesYet: 'Sin votos.', msgVotePlural1: '{n} voto', msgVotePlural2: '{n} votos', msgVotePlural3: '{n} votos', msgVotePlural5: '{n} votos', chatPollSent: 'Envió una encuesta.', chatEventError: 'Error al crear evento.', chatGeoNotSupported: 'La geolocalización no es compatible.', chatLocationSent: 'Envió una ubicación.', chatGeoError: 'No se puede recuperar la ubicación.', chatDeleteConfirm: '¿Eliminar este mensaje?', loadingOldMessages: 'Cargando...', chatEmptyTitle: 'Está muy tranquilo aquí...', chatEmptyDesc: '¡Sé el primero en enviar un mensaje!', openInMaps: 'Abrir en Google Maps', viewVotes: 'Ver votos', team: 'Equipo', tapForParticipants: 'Toca para participantes', allUsers: 'Todos', userDefault: 'Usuario', quickTexts: `["¡Apestaste hoy! 👎", "¡Buen juego! 👏", "¡Invitas las cervezas! 🍻", "¡Tarde otra vez! ⏳", "¡Aguafiestas!", "¿Quién tiene el balón?", "Excusas otra vez...", "¡Culpa del árbitro! 🙈", "¿Dónde está tu energía? 🥵", "¡A tope! 💪", "¡Necesitamos cambio! 🔄"]` },
  fr: { chatTab: 'Chat', noTeamsChatTitle: 'Vous n\'êtes dans aucune équipe.', noTeamsChatDesc: 'Rejoignez une équipe ou créez-en une.', goToTeamsBtn: 'Aller aux Équipes', noMessagesYet: 'Pas de messages...', chatPoll: 'Sondage', chatLocation: 'Emplacement', chatAttachment: 'Pièce jointe', chatDayToday: 'AUJOURD\'HUI', chatDayYesterday: 'HIER', newMessagesBadge: 'Nouveaux messages', chatTextTab: 'Texte', chatEventTab: 'Événement', chatLocationTab: 'Emplacement', pollQuestionPlaceholder: 'Quelle est la question ?...', pollAnswerPlaceholder: 'Réponse', addOption: 'Ajouter', publish: 'Publier', eventNamePlaceholder: 'Nom de l\'événement', createEventBtn: 'Créer événement', shareLocationBtn: 'Partager l\'emplacement', chatParticipants: 'Participants', noParticipants: 'Aucun participant.', adminBadge: 'Admin', onlineRecent: 'En ligne', offline: 'Hors ligne', totalVotes: 'Total', noVotesYet: 'Aucun vote.', msgVotePlural1: '{n} vote', msgVotePlural2: '{n} votes', msgVotePlural3: '{n} votes', msgVotePlural5: '{n} votes', chatPollSent: 'A envoyé un sondage.', chatEventError: 'Erreur lors de la création.', chatGeoNotSupported: 'Géolocalisation non prise en charge.', chatLocationSent: 'A envoyé un emplacement.', chatGeoError: 'Impossible d\'obtenir l\'emplacement.', chatDeleteConfirm: 'Supprimer ce message ?', loadingOldMessages: 'Chargement...', chatEmptyTitle: 'C\'est très calme ici...', chatEmptyDesc: 'Soyez le premier à envoyer un message!', openInMaps: 'Google Maps', viewVotes: 'Voir les votes', team: 'Équipe', tapForParticipants: 'Touchez pour voir les participants', allUsers: 'Tous', userDefault: 'Utilisateur', quickTexts: `["Tu as été nul aujourd'hui ! 👎", "Bon match ! 👏", "C'est ta tournée ! 🍻", "Encore en retard ! ⏳", "Rabat-joie !", "Qui a le ballon ?", "Encore des excuses...", "Faute de l'arbitre ! 🙈", "Où est l'endurance ? 🥵", "À fond ! 💪", "Il nous faut un remplaçant ! 🔄"]` },
  nl: { chatTab: 'Chat', noTeamsChatTitle: 'Je zit in geen enkel team.', noTeamsChatDesc: 'Word lid van een team of maak er een.', goToTeamsBtn: 'Naar Teams', noMessagesYet: 'Geen berichten...', chatPoll: 'Peiling', chatLocation: 'Locatie', chatAttachment: 'Bijlage', chatDayToday: 'VANDAAG', chatDayYesterday: 'GISTEREN', newMessagesBadge: 'Nieuwe berichten', chatTextTab: 'Tekst', chatEventTab: 'Evenement', chatLocationTab: 'Locatie', pollQuestionPlaceholder: 'Wat is de vraag?...', pollAnswerPlaceholder: 'Antwoord', addOption: 'Toevoegen', publish: 'Publiceren', eventNamePlaceholder: 'Evenement naam', createEventBtn: 'Evenement aanmaken', shareLocationBtn: 'Deel locatie', chatParticipants: 'Deelnemers', noParticipants: 'Geen deelnemers.', adminBadge: 'Admin', onlineRecent: 'Online', offline: 'Offline', totalVotes: 'Totaal', noVotesYet: 'Geen stemmen.', msgVotePlural1: '{n} stem', msgVotePlural2: '{n} stemmen', msgVotePlural3: '{n} stemmen', msgVotePlural5: '{n} stemmen', chatPollSent: 'Heeft een peiling gestuurd.', chatEventError: 'Fout bij aanmaken evenement.', chatGeoNotSupported: 'Geolocatie wordt niet ondersteund.', chatLocationSent: 'Heeft een locatie verzonden.', chatGeoError: 'Kan locatie niet ophalen.', chatDeleteConfirm: 'Bericht verwijderen?', loadingOldMessages: 'Laden...', chatEmptyTitle: 'Het is hier erg stil...', chatEmptyDesc: 'Stuur het eerste bericht!', openInMaps: 'Google Maps', viewVotes: 'Stemmen bekijken', team: 'Team', tapForParticipants: 'Tikken voor deelnemers', allUsers: 'Iedereen', userDefault: 'Gebruiker', quickTexts: `["Je was slecht vandaag! 👎", "Goed gespeeld! 👏", "Jij trakteert! 🍻", "Alweer te laat! ⏳", "Spelbreker!", "Wie heeft de bal?", "Weer smoesjes...", "Schuld van de scheids! 🙈", "Waar is de conditie? 🥵", "Helemaal gaan! 💪", "Wissel nodig! 🔄"]` },
  tr: { chatTab: 'Sohbet', noTeamsChatTitle: 'Henüz hiçbir takımda değilsiniz.', noTeamsChatDesc: 'Bir takıma katılın veya sohbet etmek için yeni bir tane oluşturun.', goToTeamsBtn: 'Takımlara Git', noMessagesYet: 'Henüz mesaj yok...', chatPoll: 'Anket', chatLocation: 'Konum', chatAttachment: 'Ek', chatDayToday: 'BUGÜN', chatDayYesterday: 'DÜN', newMessagesBadge: 'Yeni mesajlar', chatTextTab: 'Metin', chatEventTab: 'Etkinlik', chatLocationTab: 'Konum', pollQuestionPlaceholder: 'Soru nedir?...', pollAnswerPlaceholder: 'Cevap', addOption: 'Seçenek ekle', publish: 'Yayınla', eventNamePlaceholder: 'Etkinlik adı', createEventBtn: 'Etkinlik Oluştur', shareLocationBtn: 'Konumu paylaş', chatParticipants: 'Katılımcılar', noParticipants: 'Katılımcı yok.', adminBadge: 'Yönetici', onlineRecent: 'Son çevrimiçi', offline: 'Çevrimdışı', totalVotes: 'Toplam', noVotesYet: 'Oy yok.', msgVotePlural1: '{n} oy', msgVotePlural2: '{n} oy', msgVotePlural3: '{n} oy', msgVotePlural5: '{n} oy', chatPollSent: 'Anket gönderdi.', chatEventError: 'Oluşturma hatası.', chatGeoNotSupported: 'Desteklenmiyor.', chatLocationSent: 'Konum gönderdi.', chatGeoError: 'Alınamıyor.', chatDeleteConfirm: 'Silinsin mi?', loadingOldMessages: 'Yükleniyor...', chatEmptyTitle: 'Burası sessiz...', chatEmptyDesc: 'İlk mesajı siz gönderin!', openInMaps: 'Google Maps', viewVotes: 'Oyları görüntüle', team: 'Takım', tapForParticipants: 'Katılımcılar', allUsers: 'Herkes', userDefault: 'Kullanıcı', quickTexts: `["Berbattınız! 👎", "İyi oyun! 👏", "Biralar senden! 🍻", "Yine geç kaldın! ⏳", "Oyunbozan!", "Top kimde?", "Yine bahaneler...", "Hakem hatalı! 🙈", "Kondisyon nerede? 🥵", "Her şey tamam! 💪", "Yedeğe ihtiyacımız var! 🔄"]` },
  ar: { chatTab: 'دردشة', noTeamsChatTitle: 'لست في أي فريق بعد.', noTeamsChatDesc: 'انضم إلى فريق أو أنشئ فريقًا للدردشة.', goToTeamsBtn: 'الذهاب إلى الفرق', noMessagesYet: 'لا رسائل...', chatPoll: 'استطلاع', chatLocation: 'موقع', chatAttachment: 'مرفق', chatDayToday: 'اليوم', chatDayYesterday: 'الأمس', newMessagesBadge: 'رسائل جديدة', chatTextTab: 'نص', chatEventTab: 'حدث', chatLocationTab: 'موقع', pollQuestionPlaceholder: 'ما هو السؤال؟...', pollAnswerPlaceholder: 'إجابة', addOption: 'إضافة خيار', publish: 'نشر', eventNamePlaceholder: 'اسم الحدث', createEventBtn: 'إنشاء الحدث', shareLocationBtn: 'مشاركة الموقع', chatParticipants: 'مشاركون', noParticipants: 'لا يوجد.', adminBadge: 'مسؤول', onlineRecent: 'متصل مؤخرًا', offline: 'غير متصل', totalVotes: 'مجموع', noVotesYet: 'لا أصوات.', msgVotePlural1: '{n} صوت', msgVotePlural2: '{n} أصوات', msgVotePlural3: '{n} أصوات', msgVotePlural5: '{n} أصوات', chatPollSent: 'أرسل استطلاعاً.', chatEventError: 'خطأ.', chatGeoNotSupported: 'غير مدعوم.', chatLocationSent: 'أرسل موقعاً.', chatGeoError: 'لا يمكن الاسترداد.', chatDeleteConfirm: 'حذف؟', loadingOldMessages: 'جار التحميل...', chatEmptyTitle: 'هادئ جداً...', chatEmptyDesc: 'كن الأول!', openInMaps: 'خرائط جوجل', viewVotes: 'عرض الأصوات', team: 'فريق', tapForParticipants: 'المشاركون', allUsers: 'الكل', userDefault: 'مستخدم', quickTexts: `["لعبة سيئة! 👎", "لعبة جيدة! 👏", "تأخرت! ⏳", "من لديه الكرة؟", "أين اللياقة؟ 🥵", "نحتاج إلى تبديل! 🔄"]` },
  el: { chatTab: 'Συνομιλία', noTeamsChatTitle: 'Δεν είστε σε καμία ομάδα.', noTeamsChatDesc: 'Γίνετε μέλος.', goToTeamsBtn: 'Ομάδες', noMessagesYet: 'Κανένα μήνυμα...', chatPoll: 'Δημοσκόπηση', chatLocation: 'Τοποθεσία', chatAttachment: 'Επισύναψη', chatDayToday: 'ΣΗΜΕΡΑ', chatDayYesterday: 'ΧΘΕΣ', newMessagesBadge: 'Νέα', chatTextTab: 'Κείμενο', chatEventTab: 'Εκδήλωση', chatLocationTab: 'Τοποθεσία', pollQuestionPlaceholder: 'Ερώτηση...', pollAnswerPlaceholder: 'Απάντηση', addOption: 'Προσθήκη', publish: 'Δημοσίευση', eventNamePlaceholder: 'Όνομα', createEventBtn: 'Δημιουργία', shareLocationBtn: 'Κοινή χρήση', chatParticipants: 'Συμμετέχοντες', noParticipants: 'Κανένας.', adminBadge: 'Διαχειριστής', onlineRecent: 'Σε σύνδεση', offline: 'Εκτός', totalVotes: 'Σύνολο', noVotesYet: 'Καμία ψήφος.', msgVotePlural1: '{n} ψήφος', msgVotePlural2: '{n} ψήφοι', msgVotePlural3: '{n} ψήφοι', msgVotePlural5: '{n} ψήφοι', chatPollSent: 'Δημοσκόπηση.', chatEventError: 'Σφάλμα.', chatGeoNotSupported: 'Μη υποστηριζόμενο.', chatLocationSent: 'Τοποθεσία.', chatGeoError: 'Σφάλμα.', chatDeleteConfirm: 'Διαγραφή;', loadingOldMessages: 'Φόρτωση...', chatEmptyTitle: 'Ήσυχα...', chatEmptyDesc: 'Στείλε!', openInMaps: 'Google Maps', viewVotes: 'Ψήφοι', team: 'Ομάδα', tapForParticipants: 'Συμμετέχοντες', allUsers: 'Όλοι', userDefault: 'Χρήστης', quickTexts: `["Κακό! 👎", "Καλό παιχνίδι! 👏", "Μπύρες! 🍻", "Πάλι άργησες! ⏳", "Ποιος έχει τη μπάλα;", "Δικαιολογίες...", "Φταίει ο διαιτητής! 🙈", "Πού είναι οι δυνάμεις; 🥵", "Πάμε! 💪", "Αλλαγή! 🔄"]` }
};

masterDict.us = masterDict.en;
masterDict.at = masterDict.de;
masterDict.mx = masterDict.es;

const fileFiles = fs.readdirSync(localesDir).filter(f => f.endsWith('.ts') && f !== 'sl.ts');

fileFiles.forEach(file => {
   const langCode = file.replace('.ts', '');
   const dictToApply = masterDict[langCode];
   
   if(dictToApply) {
      let content = fs.readFileSync(path.join(localesDir, file), 'utf8');
      
      let insertion = '';
      for (const [k, v] of Object.entries(dictToApply)) {
         if(!content.includes(`${k}:`)) {
            if(k === 'quickTexts') {
               insertion += `\n    ${k}: ${v},`;
            } else {
               // Use proper string escaping for double quotes
               insertion += `\n    ${k}: "${v.replace(/"/g, '\\"')}",`;
            }
         }
      }
      
      if(insertion !== '') {
          // Add a comma after whatever preceeds the closing bracket, then insert new stuff
          content = content.replace(/([\s\n]*)(};[\s\n]*export\s+default)/, `,$1${insertion}\n$2`);
          fs.writeFileSync(path.join(localesDir, file), content);
      }
   }
});
console.log("Locales successfully mass-patched!");
